# Generated by Django 3.2.5 on 2021-07-22 14:52

from django.db import migrations
import django_ordered_field.ordered_collection_field


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_content_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='order',
            field=django_ordered_field.ordered_collection_field.OrderedCollectionField(collection=('module',), default=-1, extra_field_updates={}, self_updates_on_collection_change={}, update_auto_now=True),
        ),
    ]
