# Generated by Django 3.2.5 on 2021-07-24 12:05

from django.db import migrations
import django_ordered_field.ordered_collection_field


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=django_ordered_field.ordered_collection_field.OrderedCollectionField(collection=('course',), default=-1, extra_field_updates={}, self_updates_on_collection_change={}, update_auto_now=True),
        ),
    ]
